<?php

function spwebform_email_verify_webform_validation_validators() {
  $validators = array(
    'webform_email_verify' => array(
      'name' => t('SP webform email verify'),
      'description' => t('First it checks if the domain/host part of the e-mail exists at all, and reports an error if it does not. Second, it tries to validate the user name too, by sending a HELO/MAIL FROM/RCPT TO chain of commands to the SMTP servers for the found host.'),
      'component_types' => array(
        'email',
      ),
    ),
  );
  return $validators;
}

function spwebform_email_verify_webform_validation_validate($validator_name, $items, $components, $rule) {
  if (!empty($items) && $validator_name === 'webform_email_verify') {
    $errors = array();
    foreach ($items as $key => $val) {
      $result = sp_validate_email($val);
      if ($result !== NULL) {
        $errors[$key] = t('%item is geen bestaand e-mailadres. Controleer op tikfouten. Weet je zeker dat het e-mailadres correct is, geef dit dan door aan webmaster@sp.nl', array('%item' => $components[$key]['name']));
        watchdog('spwebform_email_verify', $result, array(), WATCHDOG_NOTICE);
      }
    }
    return $errors;
  }
}

function spwebform_email_verify_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
  switch ($key) {
  case 'spwebform_email_verify_error':
    $message['subject'] = 'SP Email verify: adres kon niet worden gecontroleerd';
    $message['body'][] = t('Rejected email address: @mail. Reason: @to', array('@mail' => $params['mail'], '@to' => $params['to']));
  }
}
